version: '3.8'

services:
  postgres:
    build: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: flask_app
    depends_on:
      - postgres
    environment:
      - FLASK_ENV=development

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
